application: go-turkey
version: 1
runtime: go
api_version: go1

handlers:
- url: /thumb/([a-fA-F0-9]){8}
  script: _go_app
- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt
- url: /egg/([0-9]+)
  static_files: img/static/thanksgiving11-egg-\1.jpg
  upload: img\/static\/thanksgiving11-egg-[0-9]+\.jpg
